use crate::{Interner, StrI};
use std::sync::Arc;

/// All Vale keywords and commonly used identifiers
/// Matches Scala's Keywords class
pub struct Keywords {
    pub func: Arc<StrI>,
    pub impoort: Arc<StrI>,
    pub export: Arc<StrI>,
    pub truue: Arc<StrI>,
    pub faalse: Arc<StrI>,
    pub own: Arc<StrI>,
    pub borrow: Arc<StrI>,
    pub weak: Arc<StrI>,
    pub share: Arc<StrI>,
    pub r#where: Arc<StrI>,
    pub additive: Arc<StrI>,
    pub inl: Arc<StrI>,
    pub heap: Arc<StrI>,
    pub imm: Arc<StrI>,
    pub r#mut: Arc<StrI>,
    pub vary: Arc<StrI>,
    pub fiinal: Arc<StrI>,
    pub exists: Arc<StrI>,
    pub resolve: Arc<StrI>,
    pub self_: Arc<StrI>,
    pub iff: Arc<StrI>,
    pub elsse: Arc<StrI>,
    pub foreeach: Arc<StrI>,
    pub r#in: Arc<StrI>,
    pub parallel: Arc<StrI>,
    pub r#break: Arc<StrI>,
    pub retuurn: Arc<StrI>,
    pub whiile: Arc<StrI>,
    pub destruct: Arc<StrI>,
    pub set: Arc<StrI>,
    pub unlet: Arc<StrI>,
    pub block: Arc<StrI>,
    pub pure: Arc<StrI>,
    pub pre: Arc<StrI>,
    pub r#unsafe: Arc<StrI>,
    pub and: Arc<StrI>,
    pub or: Arc<StrI>,
    pub r#as: Arc<StrI>,
    pub ro: Arc<StrI>,
    pub rw: Arc<StrI>,
    pub r#virtual: Arc<StrI>,
    pub r#impl: Arc<StrI>,
    pub int_capitalized: Arc<StrI>,
    pub ref_: Arc<StrI>,
    pub kind: Arc<StrI>,
    pub region: Arc<StrI>,
    pub prot: Arc<StrI>,
    pub ref_list: Arc<StrI>,
    pub ownership: Arc<StrI>,
    pub variability: Arc<StrI>,
    pub mutability: Arc<StrI>,
    pub location: Arc<StrI>,
    pub refs: Arc<StrI>,
    
    // Symbols
    pub underscore: Arc<StrI>,
    pub dot_dot: Arc<StrI>,
    
    // Built-in types
    pub int: Arc<StrI>,
    pub bool: Arc<StrI>,
    pub float: Arc<StrI>,
    pub __never: Arc<StrI>,
    pub str: Arc<StrI>,
    pub void: Arc<StrI>,
    pub i64: Arc<StrI>,
    pub i32: Arc<StrI>,
    pub i16: Arc<StrI>,
    pub i8: Arc<StrI>,
    pub u64: Arc<StrI>,
    pub u32: Arc<StrI>,
    pub u16: Arc<StrI>,
    pub u8: Arc<StrI>,
    
    // Operators
    pub plus: Arc<StrI>,
    pub asterisk: Arc<StrI>,
    pub slash: Arc<StrI>,
    pub minus: Arc<StrI>,
    pub spaceship: Arc<StrI>,
    pub less_equals: Arc<StrI>,
    pub less: Arc<StrI>,
    pub greater_equals: Arc<StrI>,
    pub greater: Arc<StrI>,
    pub triple_equals: Arc<StrI>,
    pub double_equals: Arc<StrI>,
    pub not_equals: Arc<StrI>,
    pub drop: Arc<StrI>,
    pub free: Arc<StrI>,
    pub linear: Arc<StrI>,
    pub not: Arc<StrI>,
    pub range: Arc<StrI>,
    pub begin: Arc<StrI>,
    pub next: Arc<StrI>,
    pub is_empty: Arc<StrI>,
    pub get: Arc<StrI>,
    pub underscores_call: Arc<StrI>,
    pub tuple_human_name: Vec<Arc<StrI>>,
    
    // Macros
    pub derive_struct_drop: Arc<StrI>,
    pub derive_anonymous_substruct: Arc<StrI>,
    pub derive_interface_drop: Arc<StrI>,
    
    // Generators (compiler internal)
    pub free_generator: Arc<StrI>,
    pub drop_generator: Arc<StrI>,
    pub interface_free_generator: Arc<StrI>,
    pub vale_static_sized_array_drop_into: Arc<StrI>,
    pub vale_runtime_sized_array_push: Arc<StrI>,
    pub vale_runtime_sized_array_pop: Arc<StrI>,
    pub vale_runtime_sized_array_mut_new: Arc<StrI>,
    pub vale_runtime_sized_array_capacity: Arc<StrI>,
    pub vale_runtime_sized_array_len: Arc<StrI>,
    pub vale_runtime_sized_array_imm_new: Arc<StrI>,
    pub vale_runtime_sized_array_free: Arc<StrI>,
    pub vale_runtime_sized_array_drop_into: Arc<StrI>,
    pub abstract_body: Arc<StrI>,
    pub vale_as_subtype: Arc<StrI>,
    pub vale_lock_weak: Arc<StrI>,
    pub vale_same_instance: Arc<StrI>,
    pub struct_constructor_generator: Arc<StrI>,
    pub derive_struct_constructor: Arc<StrI>,
    pub vale_static_sized_array_free: Arc<StrI>,
    pub vale_static_sized_array_len: Arc<StrI>,
    
    // Miscellaneous
    pub empty_string: Arc<StrI>,
    pub thiss: Arc<StrI>,
    pub box_human_name: Arc<StrI>,
    pub box_member_name: Arc<StrI>,
    pub t: Arc<StrI>,
    pub v: Arc<StrI>,
    pub drop_p1k: Arc<StrI>,
    pub drop_p1: Arc<StrI>,
    pub drop_r: Arc<StrI>,
    pub drop_struct: Arc<StrI>,
    pub drop_struct_template: Arc<StrI>,
    pub drop_v: Arc<StrI>,
    pub drop_vk: Arc<StrI>,
    pub free_p1: Arc<StrI>,
    pub free_struct_template: Arc<StrI>,
    pub free_struct: Arc<StrI>,
    pub free_v: Arc<StrI>,
    pub x: Arc<StrI>,
    pub d: Arc<StrI>,
    pub v_lower: Arc<StrI>,
    pub builtins: Arc<StrI>,
    pub arrays: Arc<StrI>,
    pub is_interface: Arc<StrI>,
    pub implements: Arc<StrI>,
    pub is_callable: Arc<StrI>,
    pub ref_list_compound_mutability: Arc<StrI>,
    pub any: Arc<StrI>,
    pub ifunction: Arc<StrI>,
    pub m: Arc<StrI>,
    pub e: Arc<StrI>,
    pub f: Arc<StrI>,
    pub array: Arc<StrI>,
    pub static_array: Arc<StrI>,
    pub list: Arc<StrI>,
    pub add: Arc<StrI>,
    pub opt: Arc<StrI>,
    pub some: Arc<StrI>,
    pub none: Arc<StrI>,
    pub result: Arc<StrI>,
    pub ok: Arc<StrI>,
    pub err: Arc<StrI>,
    pub functor1: Arc<StrI>,
    pub my_module: Arc<StrI>,
    pub rust: Arc<StrI>,
}

impl Keywords {
    pub fn new(interner: &Interner) -> Self {
        Keywords {
            func: interner.intern("func"),
            impoort: interner.intern("import"),
            export: interner.intern("export"),
            truue: interner.intern("true"),
            faalse: interner.intern("false"),
            own: interner.intern("own"),
            borrow: interner.intern("borrow"),
            weak: interner.intern("weak"),
            share: interner.intern("share"),
            r#where: interner.intern("where"),
            additive: interner.intern("additive"),
            inl: interner.intern("inl"),
            heap: interner.intern("heap"),
            imm: interner.intern("imm"),
            r#mut: interner.intern("mut"),
            vary: interner.intern("vary"),
            fiinal: interner.intern("final"),
            exists: interner.intern("exists"),
            resolve: interner.intern("resolve"),
            self_: interner.intern("self"),
            iff: interner.intern("if"),
            elsse: interner.intern("else"),
            foreeach: interner.intern("foreach"),
            r#in: interner.intern("in"),
            parallel: interner.intern("parallel"),
            r#break: interner.intern("break"),
            retuurn: interner.intern("return"),
            whiile: interner.intern("while"),
            destruct: interner.intern("destruct"),
            set: interner.intern("set"),
            unlet: interner.intern("unlet"),
            block: interner.intern("block"),
            pure: interner.intern("pure"),
            pre: interner.intern("pre"),
            r#unsafe: interner.intern("unsafe"),
            and: interner.intern("and"),
            or: interner.intern("or"),
            r#as: interner.intern("as"),
            ro: interner.intern("ro"),
            rw: interner.intern("rw"),
            r#virtual: interner.intern("virtual"),
            r#impl: interner.intern("impl"),
            int_capitalized: interner.intern("Int"),
            ref_: interner.intern("Ref"),
            kind: interner.intern("Kind"),
            region: interner.intern("Region"),
            prot: interner.intern("Prot"),
            ref_list: interner.intern("RefList"),
            ownership: interner.intern("Ownership"),
            variability: interner.intern("Variability"),
            mutability: interner.intern("Mutability"),
            location: interner.intern("Location"),
            refs: interner.intern("Refs"),
            underscore: interner.intern("_"),
            dot_dot: interner.intern(".."),
            int: interner.intern("int"),
            bool: interner.intern("bool"),
            float: interner.intern("float"),
            __never: interner.intern("__Never"),
            str: interner.intern("str"),
            void: interner.intern("void"),
            i64: interner.intern("i64"),
            i32: interner.intern("i32"),
            i16: interner.intern("i16"),
            i8: interner.intern("i8"),
            u64: interner.intern("u64"),
            u32: interner.intern("u32"),
            u16: interner.intern("u16"),
            u8: interner.intern("u8"),
            plus: interner.intern("+"),
            asterisk: interner.intern("*"),
            slash: interner.intern("/"),
            minus: interner.intern("-"),
            spaceship: interner.intern("<=>"),
            less_equals: interner.intern("<="),
            less: interner.intern("<"),
            greater_equals: interner.intern(">="),
            greater: interner.intern(">"),
            triple_equals: interner.intern("==="),
            double_equals: interner.intern("=="),
            not_equals: interner.intern("!="),
            drop: interner.intern("drop"),
            free: interner.intern("free"),
            linear: interner.intern("linear"),
            not: interner.intern("not"),
            range: interner.intern("range"),
            begin: interner.intern("begin"),
            next: interner.intern("next"),
            is_empty: interner.intern("isEmpty"),
            get: interner.intern("get"),
            underscores_call: interner.intern("__call"),
            tuple_human_name: vec![
                interner.intern("Tup0"),
                interner.intern("Tup1"),
                interner.intern("Tup2"),
                interner.intern("Tup3"),
                interner.intern("Tup4"),
                interner.intern("Tup5"),
                interner.intern("Tup6"),
                interner.intern("Tup7"),
                interner.intern("Tup8"),
                interner.intern("Tup9"),
            ],
            derive_struct_drop: interner.intern("DeriveStructDrop"),
            derive_anonymous_substruct: interner.intern("DeriveAnonymousSubstruct"),
            derive_interface_drop: interner.intern("DeriveInterfaceDrop"),
            free_generator: interner.intern("freeGenerator"),
            drop_generator: interner.intern("dropGenerator"),
            interface_free_generator: interner.intern("interfaceFreeGenerator"),
            vale_static_sized_array_drop_into: interner.intern("vale_static_sized_array_drop_into"),
            vale_runtime_sized_array_push: interner.intern("vale_runtime_sized_array_push"),
            vale_runtime_sized_array_pop: interner.intern("vale_runtime_sized_array_pop"),
            vale_runtime_sized_array_mut_new: interner.intern("vale_runtime_sized_array_mut_new"),
            vale_runtime_sized_array_capacity: interner.intern("vale_runtime_sized_array_capacity"),
            vale_runtime_sized_array_len: interner.intern("vale_runtime_sized_array_len"),
            vale_runtime_sized_array_imm_new: interner.intern("vale_runtime_sized_array_imm_new"),
            vale_runtime_sized_array_free: interner.intern("vale_runtime_sized_array_free"),
            vale_runtime_sized_array_drop_into: interner.intern("vale_runtime_sized_array_drop_into"),
            abstract_body: interner.intern("abstractBody"),
            vale_as_subtype: interner.intern("vale_as_subtype"),
            vale_lock_weak: interner.intern("vale_lock_weak"),
            vale_same_instance: interner.intern("vale_same_instance"),
            struct_constructor_generator: interner.intern("structConstructorGenerator"),
            derive_struct_constructor: interner.intern("DeriveStructConstructor"),
            vale_static_sized_array_free: interner.intern("vale_static_sized_array_free"),
            vale_static_sized_array_len: interner.intern("vale_static_sized_array_len"),
            empty_string: interner.intern(""),
            thiss: interner.intern("this"),
            box_human_name: interner.intern("__Box"),
            box_member_name: interner.intern("__boxee"),
            t: interner.intern("T"),
            v: interner.intern("V"),
            drop_p1k: interner.intern("DropP1K"),
            drop_p1: interner.intern("DropP1"),
            drop_r: interner.intern("DropR"),
            drop_struct: interner.intern("DropStruct"),
            drop_struct_template: interner.intern("DropStructTemplate"),
            drop_v: interner.intern("DropV"),
            drop_vk: interner.intern("DropVK"),
            free_p1: interner.intern("FreeP1"),
            free_struct_template: interner.intern("FreeStructTemplate"),
            free_struct: interner.intern("FreeStruct"),
            free_v: interner.intern("FreeV"),
            x: interner.intern("x"),
            d: interner.intern("D"),
            v_lower: interner.intern("v"),
            builtins: interner.intern("builtins"),
            arrays: interner.intern("arrays"),
            is_interface: interner.intern("isInterface"),
            implements: interner.intern("implements"),
            is_callable: interner.intern("isCallable"),
            ref_list_compound_mutability: interner.intern("refListCompoundMutability"),
            any: interner.intern("any"),
            ifunction: interner.intern("IFunction"),
            m: interner.intern("M"),
            e: interner.intern("E"),
            f: interner.intern("F"),
            array: interner.intern("Array"),
            static_array: interner.intern("StaticArray"),
            list: interner.intern("List"),
            add: interner.intern("add"),
            opt: interner.intern("Opt"),
            some: interner.intern("Some"),
            none: interner.intern("None"),
            result: interner.intern("Result"),
            ok: interner.intern("Ok"),
            err: interner.intern("Err"),
            functor1: interner.intern("Functor1"),
            my_module: interner.intern("my_module"),
            rust: interner.intern("rust"),
        }
    }
}

