use crate::interner::StrI;
use crate::Interner;

/// All Vale keywords and commonly used identifiers
/// Matches Scala's Keywords class
/// Pre-interned keyword strings.
pub struct Keywords<'a> {
  pub func: StrI<'a>,
  pub impoort: StrI<'a>,
  pub export: StrI<'a>,
  pub truue: StrI<'a>,
  pub faalse: StrI<'a>,
  pub own: StrI<'a>,
  pub borrow: StrI<'a>,
  pub weak: StrI<'a>,
  pub share: StrI<'a>,
  pub r#where: StrI<'a>,
  pub additive: StrI<'a>,
  pub inl: StrI<'a>,
  pub heap: StrI<'a>,
  pub imm: StrI<'a>,
  pub r#mut: StrI<'a>,
  pub vary: StrI<'a>,
  pub fiinal: StrI<'a>,
  pub exists: StrI<'a>,
  pub resolve: StrI<'a>,
  pub self_: StrI<'a>,
  pub iff: StrI<'a>,
  pub elsse: StrI<'a>,
  pub foreeach: StrI<'a>,
  pub r#in: StrI<'a>,
  pub parallel: StrI<'a>,
  pub r#break: StrI<'a>,
  pub retuurn: StrI<'a>,
  pub whiile: StrI<'a>,
  pub destruct: StrI<'a>,
  pub set: StrI<'a>,
  pub unlet: StrI<'a>,
  pub block: StrI<'a>,
  pub pure: StrI<'a>,
  pub pre: StrI<'a>,
  pub r#unsafe: StrI<'a>,
  pub and: StrI<'a>,
  pub or: StrI<'a>,
  pub r#as: StrI<'a>,
  pub ro: StrI<'a>,
  pub rw: StrI<'a>,
  pub r#virtual: StrI<'a>,
  pub r#impl: StrI<'a>,
  pub int_capitalized: StrI<'a>,
  pub ref_: StrI<'a>,
  pub kind: StrI<'a>,
  pub region: StrI<'a>,
  pub prot: StrI<'a>,
  pub ref_list: StrI<'a>,
  pub ownership: StrI<'a>,
  pub variability: StrI<'a>,
  pub mutability: StrI<'a>,
  pub location: StrI<'a>,
  pub refs: StrI<'a>,
  pub underscore: StrI<'a>,
  pub dot_dot: StrI<'a>,
  pub int: StrI<'a>,
  pub bool: StrI<'a>,
  pub float: StrI<'a>,
  pub __never: StrI<'a>,
  pub str: StrI<'a>,
  pub void: StrI<'a>,
  pub i64: StrI<'a>,
  pub i32: StrI<'a>,
  pub i16: StrI<'a>,
  pub i8: StrI<'a>,
  pub u64: StrI<'a>,
  pub u32: StrI<'a>,
  pub u16: StrI<'a>,
  pub u8: StrI<'a>,
  pub plus: StrI<'a>,
  pub asterisk: StrI<'a>,
  pub slash: StrI<'a>,
  pub minus: StrI<'a>,
  pub spaceship: StrI<'a>,
  pub less_equals: StrI<'a>,
  pub less: StrI<'a>,
  pub greater_equals: StrI<'a>,
  pub greater: StrI<'a>,
  pub triple_equals: StrI<'a>,
  pub double_equals: StrI<'a>,
  pub not_equals: StrI<'a>,
  pub drop: StrI<'a>,
  pub free: StrI<'a>,
  pub linear: StrI<'a>,
  pub not: StrI<'a>,
  pub range: StrI<'a>,
  pub begin: StrI<'a>,
  pub next: StrI<'a>,
  pub is_empty: StrI<'a>,
  pub get: StrI<'a>,
  pub underscores_call: StrI<'a>,
  pub tuple_human_name: Vec<StrI<'a>>,
  pub derive_struct_drop: StrI<'a>,
  pub derive_anonymous_substruct: StrI<'a>,
  pub derive_interface_drop: StrI<'a>,
  pub free_generator: StrI<'a>,
  pub drop_generator: StrI<'a>,
  pub interface_free_generator: StrI<'a>,
  pub vale_static_sized_array_drop_into: StrI<'a>,
  pub vale_runtime_sized_array_push: StrI<'a>,
  pub vale_runtime_sized_array_pop: StrI<'a>,
  pub vale_runtime_sized_array_mut_new: StrI<'a>,
  pub vale_runtime_sized_array_capacity: StrI<'a>,
  pub vale_runtime_sized_array_len: StrI<'a>,
  pub vale_runtime_sized_array_imm_new: StrI<'a>,
  pub vale_runtime_sized_array_free: StrI<'a>,
  pub vale_runtime_sized_array_drop_into: StrI<'a>,
  pub abstract_body: StrI<'a>,
  pub vale_as_subtype: StrI<'a>,
  pub vale_lock_weak: StrI<'a>,
  pub vale_same_instance: StrI<'a>,
  pub struct_constructor_generator: StrI<'a>,
  pub derive_struct_constructor: StrI<'a>,
  pub vale_static_sized_array_free: StrI<'a>,
  pub vale_static_sized_array_len: StrI<'a>,
  pub empty_string: StrI<'a>,
  pub thiss: StrI<'a>,
  pub box_human_name: StrI<'a>,
  pub box_member_name: StrI<'a>,
  pub t: StrI<'a>,
  pub v: StrI<'a>,
  pub drop_p1k: StrI<'a>,
  pub drop_p1: StrI<'a>,
  pub drop_r: StrI<'a>,
  pub drop_struct: StrI<'a>,
  pub drop_struct_template: StrI<'a>,
  pub drop_v: StrI<'a>,
  pub drop_vk: StrI<'a>,
  pub free_p1: StrI<'a>,
  pub free_struct_template: StrI<'a>,
  pub free_struct: StrI<'a>,
  pub free_v: StrI<'a>,
  pub x: StrI<'a>,
  pub d: StrI<'a>,
  pub v_lower: StrI<'a>,
  pub builtins: StrI<'a>,
  pub arrays: StrI<'a>,
  pub is_interface: StrI<'a>,
  pub implements: StrI<'a>,
  pub is_callable: StrI<'a>,
  pub ref_list_compound_mutability: StrI<'a>,
  pub any: StrI<'a>,
  pub ifunction: StrI<'a>,
  pub m: StrI<'a>,
  pub e: StrI<'a>,
  pub f: StrI<'a>,
  pub array: StrI<'a>,
  pub static_array: StrI<'a>,
  pub list: StrI<'a>,
  pub add: StrI<'a>,
  pub opt: StrI<'a>,
  pub some: StrI<'a>,
  pub none: StrI<'a>,
  pub result: StrI<'a>,
  pub ok: StrI<'a>,
  pub err: StrI<'a>,
  pub functor1: StrI<'a>,
  pub my_module: StrI<'a>,
  pub rust: StrI<'a>,
}

impl<'a> Keywords<'a> {
  pub fn new(interner: &Interner<'a>) -> Self {
    Keywords {
      func: interner.intern("func"),
      impoort: interner.intern("import"),
      export: interner.intern("export"),
      truue: interner.intern("true"),
      faalse: interner.intern("false"),
      own: interner.intern("own"),
      borrow: interner.intern("borrow"),
      weak: interner.intern("weak"),
      share: interner.intern("share"),
      r#where: interner.intern("where"),
      additive: interner.intern("additive"),
      inl: interner.intern("inl"),
      heap: interner.intern("heap"),
      imm: interner.intern("imm"),
      r#mut: interner.intern("mut"),
      vary: interner.intern("vary"),
      fiinal: interner.intern("final"),
      exists: interner.intern("exists"),
      resolve: interner.intern("resolve"),
      self_: interner.intern("self"),
      iff: interner.intern("if"),
      elsse: interner.intern("else"),
      foreeach: interner.intern("foreach"),
      r#in: interner.intern("in"),
      parallel: interner.intern("parallel"),
      r#break: interner.intern("break"),
      retuurn: interner.intern("return"),
      whiile: interner.intern("while"),
      destruct: interner.intern("destruct"),
      set: interner.intern("set"),
      unlet: interner.intern("unlet"),
      block: interner.intern("block"),
      pure: interner.intern("pure"),
      pre: interner.intern("pre"),
      r#unsafe: interner.intern("unsafe"),
      and: interner.intern("and"),
      or: interner.intern("or"),
      r#as: interner.intern("as"),
      ro: interner.intern("ro"),
      rw: interner.intern("rw"),
      r#virtual: interner.intern("virtual"),
      r#impl: interner.intern("impl"),
      int_capitalized: interner.intern("Int"),
      ref_: interner.intern("Ref"),
      kind: interner.intern("Kind"),
      region: interner.intern("Region"),
      prot: interner.intern("Prot"),
      ref_list: interner.intern("RefList"),
      ownership: interner.intern("Ownership"),
      variability: interner.intern("Variability"),
      mutability: interner.intern("Mutability"),
      location: interner.intern("Location"),
      refs: interner.intern("Refs"),
      underscore: interner.intern("_"),
      dot_dot: interner.intern(".."),
      int: interner.intern("int"),
      bool: interner.intern("bool"),
      float: interner.intern("float"),
      __never: interner.intern("__Never"),
      str: interner.intern("str"),
      void: interner.intern("void"),
      i64: interner.intern("i64"),
      i32: interner.intern("i32"),
      i16: interner.intern("i16"),
      i8: interner.intern("i8"),
      u64: interner.intern("u64"),
      u32: interner.intern("u32"),
      u16: interner.intern("u16"),
      u8: interner.intern("u8"),
      plus: interner.intern("+"),
      asterisk: interner.intern("*"),
      slash: interner.intern("/"),
      minus: interner.intern("-"),
      spaceship: interner.intern("<=>"),
      less_equals: interner.intern("<="),
      less: interner.intern("<"),
      greater_equals: interner.intern(">="),
      greater: interner.intern(">"),
      triple_equals: interner.intern("==="),
      double_equals: interner.intern("=="),
      not_equals: interner.intern("!="),
      drop: interner.intern("drop"),
      free: interner.intern("free"),
      linear: interner.intern("linear"),
      not: interner.intern("not"),
      range: interner.intern("range"),
      begin: interner.intern("begin"),
      next: interner.intern("next"),
      is_empty: interner.intern("isEmpty"),
      get: interner.intern("get"),
      underscores_call: interner.intern("__call"),
      tuple_human_name: vec![
        interner.intern("Tup0"),
        interner.intern("Tup1"),
        interner.intern("Tup2"),
        interner.intern("Tup3"),
        interner.intern("Tup4"),
        interner.intern("Tup5"),
        interner.intern("Tup6"),
        interner.intern("Tup7"),
        interner.intern("Tup8"),
        interner.intern("Tup9"),
      ],
      derive_struct_drop: interner.intern("DeriveStructDrop"),
      derive_anonymous_substruct: interner.intern("DeriveAnonymousSubstruct"),
      derive_interface_drop: interner.intern("DeriveInterfaceDrop"),
      free_generator: interner.intern("freeGenerator"),
      drop_generator: interner.intern("dropGenerator"),
      interface_free_generator: interner.intern("interfaceFreeGenerator"),
      vale_static_sized_array_drop_into: interner.intern("vale_static_sized_array_drop_into"),
      vale_runtime_sized_array_push: interner.intern("vale_runtime_sized_array_push"),
      vale_runtime_sized_array_pop: interner.intern("vale_runtime_sized_array_pop"),
      vale_runtime_sized_array_mut_new: interner.intern("vale_runtime_sized_array_mut_new"),
      vale_runtime_sized_array_capacity: interner.intern("vale_runtime_sized_array_capacity"),
      vale_runtime_sized_array_len: interner.intern("vale_runtime_sized_array_len"),
      vale_runtime_sized_array_imm_new: interner.intern("vale_runtime_sized_array_imm_new"),
      vale_runtime_sized_array_free: interner.intern("vale_runtime_sized_array_free"),
      vale_runtime_sized_array_drop_into: interner.intern("vale_runtime_sized_array_drop_into"),
      abstract_body: interner.intern("abstractBody"),
      vale_as_subtype: interner.intern("vale_as_subtype"),
      vale_lock_weak: interner.intern("vale_lock_weak"),
      vale_same_instance: interner.intern("vale_same_instance"),
      struct_constructor_generator: interner.intern("structConstructorGenerator"),
      derive_struct_constructor: interner.intern("DeriveStructConstructor"),
      vale_static_sized_array_free: interner.intern("vale_static_sized_array_free"),
      vale_static_sized_array_len: interner.intern("vale_static_sized_array_len"),
      empty_string: interner.intern(""),
      thiss: interner.intern("this"),
      box_human_name: interner.intern("__Box"),
      box_member_name: interner.intern("__boxee"),
      t: interner.intern("T"),
      v: interner.intern("V"),
      drop_p1k: interner.intern("DropP1K"),
      drop_p1: interner.intern("DropP1"),
      drop_r: interner.intern("DropR"),
      drop_struct: interner.intern("DropStruct"),
      drop_struct_template: interner.intern("DropStructTemplate"),
      drop_v: interner.intern("DropV"),
      drop_vk: interner.intern("DropVK"),
      free_p1: interner.intern("FreeP1"),
      free_struct_template: interner.intern("FreeStructTemplate"),
      free_struct: interner.intern("FreeStruct"),
      free_v: interner.intern("FreeV"),
      x: interner.intern("x"),
      d: interner.intern("D"),
      v_lower: interner.intern("v"),
      builtins: interner.intern("builtins"),
      arrays: interner.intern("arrays"),
      is_interface: interner.intern("isInterface"),
      implements: interner.intern("implements"),
      is_callable: interner.intern("isCallable"),
      ref_list_compound_mutability: interner.intern("refListCompoundMutability"),
      any: interner.intern("any"),
      ifunction: interner.intern("IFunction"),
      m: interner.intern("M"),
      e: interner.intern("E"),
      f: interner.intern("F"),
      array: interner.intern("Array"),
      static_array: interner.intern("StaticArray"),
      list: interner.intern("List"),
      add: interner.intern("add"),
      opt: interner.intern("Opt"),
      some: interner.intern("Some"),
      none: interner.intern("None"),
      result: interner.intern("Result"),
      ok: interner.intern("Ok"),
      err: interner.intern("Err"),
      functor1: interner.intern("Functor1"),
      my_module: interner.intern("my_module"),
      rust: interner.intern("rust"),
    }
  }
}
