use crate::{Interner, StrI};

/// All Vale keywords and commonly used identifiers
/// Matches Scala's Keywords class
pub struct Keywords {
    pub func: StrI,
    pub impoort: StrI,
    pub export: StrI,
    pub truue: StrI,
    pub faalse: StrI,
    pub own: StrI,
    pub borrow: StrI,
    pub weak: StrI,
    pub share: StrI,
    pub r#where: StrI,
    pub additive: StrI,
    pub inl: StrI,
    pub heap: StrI,
    pub imm: StrI,
    pub r#mut: StrI,
    pub vary: StrI,
    pub fiinal: StrI,
    pub exists: StrI,
    pub resolve: StrI,
    pub self_: StrI,
    pub iff: StrI,
    pub elsse: StrI,
    pub foreeach: StrI,
    pub r#in: StrI,
    pub parallel: StrI,
    pub r#break: StrI,
    pub retuurn: StrI,
    pub whiile: StrI,
    pub destruct: StrI,
    pub set: StrI,
    pub unlet: StrI,
    pub block: StrI,
    pub pure: StrI,
    pub pre: StrI,
    pub r#unsafe: StrI,
    pub and: StrI,
    pub or: StrI,
    pub r#as: StrI,
    pub ro: StrI,
    pub rw: StrI,
    pub r#virtual: StrI,
    pub r#impl: StrI,
    pub int_capitalized: StrI,
    pub ref_: StrI,
    pub kind: StrI,
    pub region: StrI,
    pub prot: StrI,
    pub ref_list: StrI,
    pub ownership: StrI,
    pub variability: StrI,
    pub mutability: StrI,
    pub location: StrI,
    pub refs: StrI,
    
    // Symbols
    pub underscore: StrI,
    pub dot_dot: StrI,
    
    // Built-in types
    pub int: StrI,
    pub bool: StrI,
    pub float: StrI,
    pub __never: StrI,
    pub str: StrI,
    pub void: StrI,
    pub i64: StrI,
    pub i32: StrI,
    pub i16: StrI,
    pub i8: StrI,
    pub u64: StrI,
    pub u32: StrI,
    pub u16: StrI,
    pub u8: StrI,
    
    // Operators
    pub plus: StrI,
    pub asterisk: StrI,
    pub slash: StrI,
    pub minus: StrI,
    pub spaceship: StrI,
    pub less_equals: StrI,
    pub less: StrI,
    pub greater_equals: StrI,
    pub greater: StrI,
    pub triple_equals: StrI,
    pub double_equals: StrI,
    pub not_equals: StrI,
    pub drop: StrI,
    pub free: StrI,
    pub linear: StrI,
    pub not: StrI,
    pub range: StrI,
    pub begin: StrI,
    pub next: StrI,
    pub is_empty: StrI,
    pub get: StrI,
    pub underscores_call: StrI,
    pub tuple_human_name: Vec<StrI>,
    
    // Macros
    pub derive_struct_drop: StrI,
    pub derive_anonymous_substruct: StrI,
    pub derive_interface_drop: StrI,
    
    // Generators (compiler internal)
    pub free_generator: StrI,
    pub drop_generator: StrI,
    pub interface_free_generator: StrI,
    pub vale_static_sized_array_drop_into: StrI,
    pub vale_runtime_sized_array_push: StrI,
    pub vale_runtime_sized_array_pop: StrI,
    pub vale_runtime_sized_array_mut_new: StrI,
    pub vale_runtime_sized_array_capacity: StrI,
    pub vale_runtime_sized_array_len: StrI,
    pub vale_runtime_sized_array_imm_new: StrI,
    pub vale_runtime_sized_array_free: StrI,
    pub vale_runtime_sized_array_drop_into: StrI,
    pub abstract_body: StrI,
    pub vale_as_subtype: StrI,
    pub vale_lock_weak: StrI,
    pub vale_same_instance: StrI,
    pub struct_constructor_generator: StrI,
    pub derive_struct_constructor: StrI,
    pub vale_static_sized_array_free: StrI,
    pub vale_static_sized_array_len: StrI,
    
    // Miscellaneous
    pub empty_string: StrI,
    pub thiss: StrI,
    pub box_human_name: StrI,
    pub box_member_name: StrI,
    pub t: StrI,
    pub v: StrI,
    pub drop_p1k: StrI,
    pub drop_p1: StrI,
    pub drop_r: StrI,
    pub drop_struct: StrI,
    pub drop_struct_template: StrI,
    pub drop_v: StrI,
    pub drop_vk: StrI,
    pub free_p1: StrI,
    pub free_struct_template: StrI,
    pub free_struct: StrI,
    pub free_v: StrI,
    pub x: StrI,
    pub d: StrI,
    pub v_lower: StrI,
    pub builtins: StrI,
    pub arrays: StrI,
    pub is_interface: StrI,
    pub implements: StrI,
    pub is_callable: StrI,
    pub ref_list_compound_mutability: StrI,
    pub any: StrI,
    pub ifunction: StrI,
    pub m: StrI,
    pub e: StrI,
    pub f: StrI,
    pub array: StrI,
    pub static_array: StrI,
    pub list: StrI,
    pub add: StrI,
    pub opt: StrI,
    pub some: StrI,
    pub none: StrI,
    pub result: StrI,
    pub ok: StrI,
    pub err: StrI,
    pub functor1: StrI,
    pub my_module: StrI,
    pub rust: StrI,
}

impl Keywords {
    pub fn new(interner: &mut Interner) -> Self {
        Keywords {
            func: interner.intern("func"),
            impoort: interner.intern("import"),
            export: interner.intern("export"),
            truue: interner.intern("true"),
            faalse: interner.intern("false"),
            own: interner.intern("own"),
            borrow: interner.intern("borrow"),
            weak: interner.intern("weak"),
            share: interner.intern("share"),
            r#where: interner.intern("where"),
            additive: interner.intern("additive"),
            inl: interner.intern("inl"),
            heap: interner.intern("heap"),
            imm: interner.intern("imm"),
            r#mut: interner.intern("mut"),
            vary: interner.intern("vary"),
            fiinal: interner.intern("final"),
            exists: interner.intern("exists"),
            resolve: interner.intern("resolve"),
            self_: interner.intern("self"),
            iff: interner.intern("if"),
            elsse: interner.intern("else"),
            foreeach: interner.intern("foreach"),
            r#in: interner.intern("in"),
            parallel: interner.intern("parallel"),
            r#break: interner.intern("break"),
            retuurn: interner.intern("return"),
            whiile: interner.intern("while"),
            destruct: interner.intern("destruct"),
            set: interner.intern("set"),
            unlet: interner.intern("unlet"),
            block: interner.intern("block"),
            pure: interner.intern("pure"),
            pre: interner.intern("pre"),
            r#unsafe: interner.intern("unsafe"),
            and: interner.intern("and"),
            or: interner.intern("or"),
            r#as: interner.intern("as"),
            ro: interner.intern("ro"),
            rw: interner.intern("rw"),
            r#virtual: interner.intern("virtual"),
            r#impl: interner.intern("impl"),
            int_capitalized: interner.intern("Int"),
            ref_: interner.intern("Ref"),
            kind: interner.intern("Kind"),
            region: interner.intern("Region"),
            prot: interner.intern("Prot"),
            ref_list: interner.intern("RefList"),
            ownership: interner.intern("Ownership"),
            variability: interner.intern("Variability"),
            mutability: interner.intern("Mutability"),
            location: interner.intern("Location"),
            refs: interner.intern("Refs"),
            underscore: interner.intern("_"),
            dot_dot: interner.intern(".."),
            int: interner.intern("int"),
            bool: interner.intern("bool"),
            float: interner.intern("float"),
            __never: interner.intern("__Never"),
            str: interner.intern("str"),
            void: interner.intern("void"),
            i64: interner.intern("i64"),
            i32: interner.intern("i32"),
            i16: interner.intern("i16"),
            i8: interner.intern("i8"),
            u64: interner.intern("u64"),
            u32: interner.intern("u32"),
            u16: interner.intern("u16"),
            u8: interner.intern("u8"),
            plus: interner.intern("+"),
            asterisk: interner.intern("*"),
            slash: interner.intern("/"),
            minus: interner.intern("-"),
            spaceship: interner.intern("<=>"),
            less_equals: interner.intern("<="),
            less: interner.intern("<"),
            greater_equals: interner.intern(">="),
            greater: interner.intern(">"),
            triple_equals: interner.intern("==="),
            double_equals: interner.intern("=="),
            not_equals: interner.intern("!="),
            drop: interner.intern("drop"),
            free: interner.intern("free"),
            linear: interner.intern("linear"),
            not: interner.intern("not"),
            range: interner.intern("range"),
            begin: interner.intern("begin"),
            next: interner.intern("next"),
            is_empty: interner.intern("isEmpty"),
            get: interner.intern("get"),
            underscores_call: interner.intern("__call"),
            tuple_human_name: vec![
                interner.intern("Tup0"),
                interner.intern("Tup1"),
                interner.intern("Tup2"),
                interner.intern("Tup3"),
                interner.intern("Tup4"),
                interner.intern("Tup5"),
                interner.intern("Tup6"),
                interner.intern("Tup7"),
                interner.intern("Tup8"),
                interner.intern("Tup9"),
            ],
            derive_struct_drop: interner.intern("DeriveStructDrop"),
            derive_anonymous_substruct: interner.intern("DeriveAnonymousSubstruct"),
            derive_interface_drop: interner.intern("DeriveInterfaceDrop"),
            free_generator: interner.intern("freeGenerator"),
            drop_generator: interner.intern("dropGenerator"),
            interface_free_generator: interner.intern("interfaceFreeGenerator"),
            vale_static_sized_array_drop_into: interner.intern("vale_static_sized_array_drop_into"),
            vale_runtime_sized_array_push: interner.intern("vale_runtime_sized_array_push"),
            vale_runtime_sized_array_pop: interner.intern("vale_runtime_sized_array_pop"),
            vale_runtime_sized_array_mut_new: interner.intern("vale_runtime_sized_array_mut_new"),
            vale_runtime_sized_array_capacity: interner.intern("vale_runtime_sized_array_capacity"),
            vale_runtime_sized_array_len: interner.intern("vale_runtime_sized_array_len"),
            vale_runtime_sized_array_imm_new: interner.intern("vale_runtime_sized_array_imm_new"),
            vale_runtime_sized_array_free: interner.intern("vale_runtime_sized_array_free"),
            vale_runtime_sized_array_drop_into: interner.intern("vale_runtime_sized_array_drop_into"),
            abstract_body: interner.intern("abstractBody"),
            vale_as_subtype: interner.intern("vale_as_subtype"),
            vale_lock_weak: interner.intern("vale_lock_weak"),
            vale_same_instance: interner.intern("vale_same_instance"),
            struct_constructor_generator: interner.intern("structConstructorGenerator"),
            derive_struct_constructor: interner.intern("DeriveStructConstructor"),
            vale_static_sized_array_free: interner.intern("vale_static_sized_array_free"),
            vale_static_sized_array_len: interner.intern("vale_static_sized_array_len"),
            empty_string: interner.intern(""),
            thiss: interner.intern("this"),
            box_human_name: interner.intern("__Box"),
            box_member_name: interner.intern("__boxee"),
            t: interner.intern("T"),
            v: interner.intern("V"),
            drop_p1k: interner.intern("DropP1K"),
            drop_p1: interner.intern("DropP1"),
            drop_r: interner.intern("DropR"),
            drop_struct: interner.intern("DropStruct"),
            drop_struct_template: interner.intern("DropStructTemplate"),
            drop_v: interner.intern("DropV"),
            drop_vk: interner.intern("DropVK"),
            free_p1: interner.intern("FreeP1"),
            free_struct_template: interner.intern("FreeStructTemplate"),
            free_struct: interner.intern("FreeStruct"),
            free_v: interner.intern("FreeV"),
            x: interner.intern("x"),
            d: interner.intern("D"),
            v_lower: interner.intern("v"),
            builtins: interner.intern("builtins"),
            arrays: interner.intern("arrays"),
            is_interface: interner.intern("isInterface"),
            implements: interner.intern("implements"),
            is_callable: interner.intern("isCallable"),
            ref_list_compound_mutability: interner.intern("refListCompoundMutability"),
            any: interner.intern("any"),
            ifunction: interner.intern("IFunction"),
            m: interner.intern("M"),
            e: interner.intern("E"),
            f: interner.intern("F"),
            array: interner.intern("Array"),
            static_array: interner.intern("StaticArray"),
            list: interner.intern("List"),
            add: interner.intern("add"),
            opt: interner.intern("Opt"),
            some: interner.intern("Some"),
            none: interner.intern("None"),
            result: interner.intern("Result"),
            ok: interner.intern("Ok"),
            err: interner.intern("Err"),
            functor1: interner.intern("Functor1"),
            my_module: interner.intern("my_module"),
            rust: interner.intern("rust"),
        }
    }
}

